import '@/app/globals.css';

export const metadata = {
  title: 'Celebrity Visual Stories | Lifestyle Web Stories | Tech Tips & Tricks – Sadaiv Satya',
  description: 'Generated by Next.js',
  icons: {
    icon: '/images/logo.webp',
    apple: '/apple-touch-icon.png',
    other: [
      { rel: 'icon', url: '/favicon-32x32.png', sizes: '32x32' },
      { rel: 'icon', url: '/favicon-16x16.png', sizes: '16x16' },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
